channels:
- conda-forge
- anaconda
dependencies:
- python=3.9.23
- pip:
  - adal==1.2.7
  - annotated-types==0.7.0
  - applicationinsights==0.11.10
  - arch==5.6.0
  - argcomplete==3.6.2
  - asttokens==3.0.0
  - attrs==25.3.0
  - azure-common==1.1.28
  - azure-core==1.34.0
  - azure-graphrbac==0.61.2
  - azure-identity==1.23.0
  - azure-mgmt-authorization==4.0.0
  - azure-mgmt-containerregistry==13.0.0
  - azure-mgmt-core==1.5.0
  - azure-mgmt-keyvault==11.0.0
  - azure-mgmt-network==29.0.0
  - azure-mgmt-resource==24.0.0
  - azure-mgmt-storage==23.0.0
  - azure-storage-blob==12.19.0
  - azure-storage-queue==12.12.0
  - azureml-automl-core==1.60.0
  - azureml-automl-runtime==1.60.0
  - azureml-core==1.60.0.post1
  - azureml-dataprep==5.1.6
  - azureml-dataprep-native==41.0.0
  - azureml-dataprep-rslex==2.22.5
  - azureml-dataset-runtime==1.60.0
  - azureml-defaults==1.60.0
  - azureml-inference-server-http==1.4.1
  - azureml-interpret==1.60.0
  - azureml-mlflow==1.60.0.post1
  - azureml-pipeline-core==1.60.0
  - azureml-responsibleai==1.60.0
  - azureml-telemetry==1.60.0
  - azureml-train-automl==1.60.0
  - azureml-train-automl-client==1.60.0
  - azureml-train-automl-runtime==1.60.0
  - azureml-train-core==1.60.0
  - azureml-train-restclients-hyperdrive==1.60.0
  - azureml-training-tabular==1.60.0
  - backports-tempfile==1.0
  - backports-weakref==1.0.post1
  - bcrypt==4.3.0
  - blinker==1.9.0
  - bokeh==2.4.3
  - cachetools==5.5.2
  - certifi==2025.6.15
  - cffi==1.17.1
  - charset-normalizer==3.4.2
  - cmdstanpy==1.2.5
  - coloredlogs==15.0.1
  - comm==0.2.2
  - contextlib2==21.6.0
  - contourpy==1.3.0
  - convertdate==2.4.0
  - cryptography==45.0.4
  - cycler==0.12.1
  - cython==3.1.2
  - dask==2023.2.0
  - databricks-sdk==0.57.0
  - dataclasses==0.6
  - debugpy==1.8.14
  - decorator==5.2.1
  - dice-ml==0.11
  - dill==0.3.9
  - distributed==2023.2.0
  - distro==1.9.0
  - docker==7.1.0
  - dotnetcore2==3.1.23
  - econml==0.15.1
  - entrypoints==0.4
  - ephem==4.2
  - erroranalysis==0.5.5
  - exceptiongroup==1.3.0
  - executing==2.2.0
  - fairlearn==0.7.0
  - fire==0.7.0
  - flask==3.1.1
  - flask-cors==6.0.1
  - flatbuffers==25.2.10
  - fonttools==4.58.4
  - fusepy==3.0.1
  - gensim==4.3.2
  - gitdb==4.0.12
  - gitpython==3.1.44
  - google-api-core==2.25.1
  - google-auth==2.40.3
  - googleapis-common-protos==1.70.0
  - gunicorn==23.0.0
  - humanfriendly==10.0
  - idna==3.10
  - importlib-metadata==7.2.1
  - importlib-resources==6.4.0
  - inference-schema==1.8
  - interpret-community==0.31.0
  - interpret-core==0.5.0
  - ipykernel==6.29.5
  - ipython==8.18.1
  - isodate==0.7.2
  - itsdangerous==2.2.0
  - jedi==0.19.2
  - jeepney==0.9.0
  - jmespath==0.10.0
  - jsonpickle==4.1.1
  - jsonschema==4.24.0
  - jsonschema-specifications==2025.4.1
  - jupyter-client==8.6.3
  - jupyter-core==5.8.1
  - keras2onnx==1.6.0
  - kiwisolver==1.4.7
  - knack==0.12.0
  - lightgbm==4.6.0
  - locket==1.0.0
  - lunarcalendar==0.0.9
  - matplotlib==3.9.4
  - matplotlib-inline==0.1.7
  - ml-wrappers==0.5.6
  - mlflow-skinny==2.15.1
  - mltable==1.6.1
  - msal==1.32.3
  - msal-extensions==1.3.1
  - msgpack==1.1.1
  - msrest==0.7.1
  - msrestazure==0.6.4.post1
  - ndg-httpsclient==0.5.1
  - nest-asyncio==1.6.0
  - networkx==2.5
  - numba==0.56.4
  - oauthlib==3.3.1
  - onnx==1.17.0
  - onnxconverter-common==1.13.0
  - onnxmltools==1.12.0
  - onnxruntime==1.17.3
  - opencensus==0.11.4
  - opencensus-context==0.1.3
  - opencensus-ext-azure==1.1.15
  - opentelemetry-api==1.34.1
  - opentelemetry-sdk==1.34.1
  - opentelemetry-semantic-conventions==0.55b1
  - packaging==24.2
  - paramiko==3.5.1
  - parso==0.8.4
  - partd==1.4.2
  - pathspec==0.12.1
  - patsy==1.0.1
  - pexpect==4.9.0
  - pillow==11.2.1
  - pkginfo==1.12.1.2
  - platformdirs==4.3.8
  - pmdarima==1.8.5
  - prompt-toolkit==3.0.51
  - property-cached==1.6.4
  - prophet==1.1.4
  - proto-plus==1.26.1
  - protobuf==5.29.5
  - ptyprocess==0.7.0
  - pure-eval==0.2.3
  - pyarrow==14.0.2
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.2
  - pycparser==2.22
  - pydantic==2.11.7
  - pydantic-core==2.33.2
  - pydantic-settings==2.9.1
  - pygments==2.19.1
  - pyjwt==2.10.1
  - pymeeus==0.5.12
  - pynacl==1.5.0
  - pyopenssl==25.1.0
  - pyparsing==3.2.3
  - pysocks==1.7.1
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.1.0
  - pytz==2024.2
  - pyyaml==6.0.2
  - pyzmq==27.0.0
  - raiutils==0.4.2
  - referencing==0.36.2
  - requests==2.32.4
  - requests-oauthlib==2.0.0
  - responsibleai==0.36.0
  - rpds-py==0.25.1
  - rsa==4.9.1
  - s3transfer==0.5.2
  - scipy==1.10.1
  - secretstorage==3.3.3
  - semver==2.13.0
  - six==1.17.0
  - skl2onnx==1.15.0
  - sklearn-pandas==1.7.0
  - slicer==0.0.7
  - smart-open==6.4.0
  - smmap==5.0.2
  - sortedcontainers==2.4.0
  - sparse==0.15.5
  - sqlparse==0.5.3
  - stack-data==0.6.3
  - stanio==0.5.1
  - statsmodels==0.13.5
  - tabulate==0.9.0
  - tblib==3.1.0
  - termcolor==3.1.0
  - threadpoolctl==3.6.0
  - toolz==1.0.0
  - tornado==6.5.1
  - tqdm==4.67.1
  - traitlets==5.14.3
  - typing-inspection==0.4.1
  - urllib3==1.26.20
  - wcwidth==0.2.13
  - werkzeug==3.1.3
  - wrapt==1.16.0
  - xgboost==1.5.2
  - zict==3.0.0
  - zipp==3.23.0
- boto3=1.20.19
- botocore=1.23.19
- bzip2=1.0.8
- ca-certificates=2025.6.15
- cloudpickle=2.2.1
- cpython=3.9.23
- filelock=3.18.0
- fsspec=2025.5.1
- gmp=6.3.0
- gmpy2=2.2.1
- holidays=0.75
- icu=75.1
- jinja2=3.1.6
- joblib=1.2.0
- libabseil=20250127.1
- libexpat=2.7.0
- libffi=3.4.6
- libgcc=15.1.0
- libhwloc=2.11.2
- libiconv=1.18
- liblzma=5.8.1
- libnsl=2.0.1
- libprotobuf=5.29.3
- libsqlite=3.50.1
- libstdcxx=15.1.0
- libtorch=2.6.0
- libuuid=2.38.1
- libuv=1.51.0
- libxcrypt=4.4.36
- libxml2=2.13.8
- libzlib=1.3.1
- llvm-openmp=20.1.7
- llvmlite=0.39.1
- markupsafe=3.0.2
- mkl=2024.2.2
- mpc=1.3.1
- mpfr=4.2.1
- mpmath=1.3.0
- numpy=1.23.5
- optree=0.16.0
- pandas=1.5.3
- pip=25.1.1
- psutil=5.9.3
- py-cpuinfo=5.0.0
- pybind11=2.13.6
- pybind11-global=2.13.6
- python_abi=3.9
- pytorch=2.6.0
- scikit-learn=1.5.1
- setuptools=78.1.1
- setuptools-git=1.2
- sleef=3.8
- sympy=1.14.0
- tbb=2021.13.0
- typing-extensions=4.14.0
- typing_extensions=4.14.0
- tzdata=2025b
- wheel=0.45.1
name: project_environment
